import { Card } from "../contracts/card";

export const cards: Card[] = [
  {
    id: 1,
    tipo: "definicao",
    categoria: "visual",
    descricao: "Deficiência visual abrange pessoas cegas e pessoas com visão reduzida.",
    pontos: 1,
    coracoes: 1,
    bonus: false,
  },
  {
    id: 2,
    tipo: "informacao",
    categoria: "auditiva",
    descricao: "O termo correto é 'Surdo' e não 'Surdo-mudo'. A mudez é uma outra deficiência.",
    pontos: 1,
    coracoes: 2,
    bonus: true,
  },
  {
    id: 3,
    tipo: "pessoa",
    categoria: "física",
    descricao: "Jillian Mercado é uma modelo americana com distrofia muscular, que se interessou pelo mundo da moda devido à sua mãe, costureira, e seu pai, vendedor de calçados.",
    pontos: 1,
    coracoes: 1,
    bonus: false,
  },
  {
    id: 4,
    tipo: "ação",
    categoria: "intelectual",
    descricao: "A pessoa com deficiência intelectual deve fazer sozinha tudo o que puder, e devemos ajudá-la somente se for necessário.",
    pontos: 2,
    coracoes: 3,
    bonus: true,
  },
  {
    id: 5,
    tipo: "filme",
    categoria: "tea",
    descricao: "Temple Grandin (2010) - Baseado no livro “Uma menina estranha”, da própria Temple, uma mulher com autismo que se tornou uma das maiores especialistas do mundo em manejo de gado.",
    pontos: 1,
    coracoes: 1,
    bonus: false,
  },
  {
    id: 6,
    tipo: "informação",
    categoria: "genérica",
    descricao: "Deficiência é o termo usado para definir a ausência ou a disfunção de uma estrutura psíquica, fisiológica ou anatômica.",
    pontos: 1,
    coracoes: 2,
    bonus: false,
  },
];
